version: '3.8'

services:
  # Main API service
  vendor-api:
    build: .
    container_name: vendor-qualification-api
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vendor-qualification-network 